# Generated by Django 3.2.7 on 2021-12-01 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commodityid', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('subcategory', models.CharField(blank=True, max_length=64)),
                ('numofstock', models.IntegerField(default=0)),
                ('onsale', models.BooleanField(default=True)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('selectedbuyer', models.CharField(max_length=128)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Commodities',
            },
        ),
        migrations.CreateModel(
            name='CommodityType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1024)),
                ('commodityid', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=48)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=28)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('avatarurl', models.CharField(max_length=128)),
                ('likecommoditylist', models.CharField(blank=True, max_length=4096)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('message', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField()),
                ('buyer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Shop.user')),
                ('commodity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Shop.commodity')),
            ],
            options={
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='CompletedOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('completeDate', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.message')),
            ],
        ),
        migrations.AddField(
            model_name='commodity',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Shop.user'),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=48)),
                ('isCompleted', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.message')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.user')),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.user')),
            ],
        ),
    ]
